# -*- coding: utf-8 -*-
"""Trilha3-Aulas-Toledo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fRTSquPVcz3CRczAn3ualwdtvqJNgQlJ
"""

#Manipulação de Strings
#Alguns dos Recurso e o que podemos fazer para manipular as string

aux = 'Alessandra Sandeski'
type(aux)
#NÃO É POSSÍVEL MUDAR UMA LETRA DE UMA STRING MAS CONSIGO TRANSFORMAR UMA STRING EM UMA LISTA AI SIM É POSSÍVEL ALTERAR SEU VALOR
lista = list(aux)
print(lista)
lista[0] = 'B'
print(lista)

frutas = 'Banana', 'Laranja', 'Melancia' #conversão tipo list
lista_frutas = list(frutas)
print(lista_frutas)
lista_frutas[1] = 'Abacaxi'
print(lista_frutas)

#verificações na string
aux.startswith('Ale')#Retorna verdadeiro ou false conferindo se começa com Ale
teste = 'A Lataria do carro esta amassada'#conferindo o que esta no final se termina com a palavra amassada
teste.endswith("amassada")
aux.lower()#a propriedade lower devolve toda a string em MINÚSCULA
aux.upper()#devolve toda a string em MAIUSCULA
#NAVEGANDO RAPIDAMENTE DENTRO DE UMA STRING

'Sandeski' in aux #true pq esta lá em AUX
'Sandeski' not in aux#retorna false não esta em aux false pq ele esta lá

#É possível contar quantas vezes uma palavra aparece em uma string
texto = 'um tigre, dois tigres, três tigres'
tx = texto.count('tigres')
print(tx)
tt = texto.count('tigre')
print(tt)
mm = texto.count('t')
print(mm)
hh = texto.find('tig')#MOSTRA A POSIÇÃO O INDICE 3
print(hh)
ff = texto.split(',') #define a variavel com a separação das virgulas
print(ff)
bb = texto.replace('tigre', 'gato')
print(bb)
entrada = '    Olá '
entrada.strip()

#OPERAÇÕES EM STRING - PARTE 2
nome = 'Alessandra'
idade = 29
salario = 8950.30 #utilizo ponto e nunca virgula
print(f'{nome.upper()} é programadora em linguagem Python, tem {idade:04} anos, com um salário iniciado em R$ {salario:5.2f}') #EXIBIÇÃO COM MAIOR ELEGÂNCIA PARA O USUÁRIO!

s = "python"
excl = "!"
print(s+excl*3)

teste_agora = "Toledo’s PP"
len(teste_agora)

minha_string = "Toledo’s PP"
comprimento = len(minha_string)
print(comprimento)  # Isso imprimirá 10

a = 'Exane'
a = a.replace('n', 'm')
print(a)

"""Arquivos
Modos de abertura de arquivos:
'r': leitura
'w': escrita, apaga o conteúdo se já existir
'a': escrita, mas preserva o conteúdo se ja existir
'b': modo binário
'+': atualização(leitura e escrita)
"""

#COMO ESCREVO EM UM ARQUIVO TEXTO E COMO RECUPERO E COMO POSSO PERSISTIR DADOS EM UM ARQUIVO DO TIPO TEXTO
#CRIANDO UM ARQUIVO TEXTO PYTHON SALVANDO NO ARQUIVO TEXTO
arquivo = open('dados.txt', 'w')
for linha in range(1,101):
    arquivo.write(f'Linha {linha}\n')
arquivo.close()

#LEITURA DE ARQUIVO
arquivo = open('dados.txt', 'r')
for linhas in arquivo.readlines():
    print(linhas)
arquivo.close()

#CRIANDO A AGENDA TELEFÔNICA

agenda = [] #TRABALHA COM UMA LISTA

def nome(): #FUNÇÃO QUE PEDE O NOME
    return input('Nome: ')

def telefone(): #FUNÇÃO QUE PEDE O TELEFONE
    return input('Telefone: ')

def mostra_nome_telefone(nome, telefone): #FUNÇÃO QUE MOSTRA OS DADOS CONCATENANDO
    print(f'Nomw: {nome} Telefone: {telefone}')

def nome_arquivo(): #FUNÇÃO QUE PEDE UM NOME DO ARQUIVO
    return input('Nome do arquivo: ')

def pesquisa(nome):
    mnome = nome.lower()
    #na variável mnome guardo nome em Maiuscula
    for p, e in enumerate(agenda):
        if[0].lower() == mnome:
            return p
    return None

def novo():
    global agenda
    nome = pede_nome()
    telefone = pede_telefone()
    agenda.append([nome, telefone])

def apaga():
    global agenda
    nome = pede_nome